name: 'bigquery_analytics'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  bigquery_analytics:
    staging:
    +persist_docs:
      relation: true
      columns: true
    staging:
      +materialized: table
      schema: "{{ env_var('DBT_TRGT_SCHEMA') }}"
      database: practical-link-432506-b0
    marts:
      +materialized: table
      schema: "{{ env_var('DBT_TRGT_SCHEMA') }}"
      database: "{{ env_var('DBT_TRGT_DB_MARTS') }}"
      #database: "{% if target.name == 'prod' %} silver-433308 {% else %} practical-link-432506-b0 {% endif %}"
    metrics:
      +materialized: table
      schema: "{{ env_var('DBT_TRGT_SCHEMA') }}"
      database: "{{ env_var('DBT_TRGT_DB_METRICS') }}"
      #database: "{% if target.name == 'prod' %} gold-433308 {% else %} practical-link-432506-b0 {% endif %}"
      